### ISSUE TITLE
🤖Разработка бота по ТЗ заказчика.

### ISSUE THREAD

**Issue by nikitapatrakov** [Studio-Yandex-Practicum/dementia_bot#78]
Требуется разработать бота по схема заказчика:
![2024-04-09 17 46 28](https://github.com/Studio-Yandex-Practicum/dementia_bot/assets/93661510/b8a87c04-81be-4869-8a05-0bc4d1225c10)
1. Информация о боте. Предлагаю взять с сайта описание организации.https://xn--d1acamsh7dwd.net
2. Приветствие . Тоже думаю возьмем с сайта информацию о деменции.
3. Тестирование. https://testing.xn--d1acamsh7dwd.net/testUser требуется только этот тест. Предлагаю попробовать его реализовать webapp.

**Comment by ZhdanovAM72** [comment]
Направлен [PR](https://github.com/Studio-Yandex-Practicum/dementia_bot/pull/79)
