### ISSUE TITLE
Продумать алгоритм реализации передачи теста по API

### ISSUE THREAD

**Issue by nikitapatrakov** [Studio-Yandex-Practicum/dementia_bot#8]
Why?
Продумать алгоритм реализации передачи теста по API

How to do?
Найти лучшее решение по передаче теста с вопросами бота примеры реализации:
    1. Передавать тест с вопросами одним json
            (в админке появились формы для заполения вопросов и тестов)        
![Снимок экрана 2023-09-17 в 13 48 34](https://github.com/Studio-Yandex-Practicum/dementia_bot/assets/93661510/6692aa62-8701-412b-9a74-0243814c8c66)
Используем библиотеку DRF (документация доступна по ссылке: https://www.django-rest-framework.org/topics/documenting-your-api/, ссылка на теорию в Яндекс практикуме: https://practicum.yandex.ru/learn/python-developer-plus/courses/9527ae09-177e-42cc-95fa-cd6a94de2352/sprints/52276/topics/5ea1635f-38e3-46e4-a2f7-cf66e430833d/lessons/8399f459-4592-4cc9-a5cf-92301d794cea/
Делаем возможность передачи теста json файлом:
![Снимок экрана 2023-09-17 в 14 40 03](https://github.com/Studio-Yandex-Practicum/dementia_bot/assets/93661510/34b0af8b-dc8f-40d9-a35d-084942f4bcf3)

образец

    2. Передавать по одному вопросу и получать ссылку на след вопрос

Where?
"Django", "Bot"

Чек-лист

От up-to-date ветки develop создать свою ветку feature/your_work_name (если задача на новую фичу) или fix/your_work_name (если задача на правку бага)

Перед тем, как сделать git add . своей ветки:
проверить, что в коммит не попадают служебные файлы/папки - если такие файлы появились, добавить их в .gitignore перед коммитом

Перед тем, как сделать git push своей ветки:

закоммитить правки из своей локальной ветки (но не пушить)
проверить, что в ветке develop самый актуальный код (git checkout develop, git pull)
смержить код из develop в свою ветку (git checkout ваша ветка, git merge develop), порешать все конфликты
проверить, что ваш код работает после объединения с кодом из develop
отправить коммит в удаленный репозиторий
Перед тем, как создать PR в git:
открыть в браузере, дождаться проверок (если они есть), нажать на копку Create pull request
в описании PR коротко перечислить правки, можно приложить ссылку на задачу из ноушена
подтвердить создание PR
не мержить свою ветку в develop (НЕ нажимать зеленую кнопку Merge pull request)

**Comment by nikitapatrakov** [comment]
Привет, как у тебя идет процесс работы ??

**Comment by VladPetukhin** [comment]
привет. в принципе? или здесь. это задачу сделал, отправил
